### ISSUE TITLE
consider using xxHash instead of sha1

### ISSUE THREAD

**Issue by rhetr** [Jwink3101/PyFiSync#2]
https://github.com/Cyan4973/xxHash#benchmarks

**Comment by Jwink3101** [comment]
A major design goal of PyFiSync is to have as close to zero external dependencies as possible. As it stands now, there are none for regular mode and just the  rclone executable for rclone mode. Until Python includes xxHash in the standard library, or there is an acceptably licensed, pure-python implementation I can include in the source, I do not think it is worth adding.

If rclone implemented it, I would also reconsider assuming there was a performant way to handle it.

As a general note, when using PyFiSync with sha1, it caches sha1's for files that are very likely unmodified (acceptable for general use, but there is obviously an easy pathological case). So computing sha1 is pretty fast since it is only on modified files.

Also, when working with rclone, just because you use sha1 (`hash.sha1`) on the remote, it does not mean it has to be used on the local. Comparisons are based on mtime. Hashes are just used for file tracking.

If am going to close this for now but I am willing to reconsider it in the future.
